In [1]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [3]:
for n = [1,2,5]
    println(n)
end

1
2
5


In [6]:
m, n = 5, 5
A = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [7]:
for i in 1:m
    for j in 1:n
        A[i, j] = i+j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [8]:
for i in 1:m, j in 1:n
    A[i, j] = i+j
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [9]:
A = [i+j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [10]:
display(A)

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [11]:
println(A)

[2 3 4 5 6; 3 4 5 6 7; 4 5 6 7 8; 5 6 7 8 9; 6 7 8 9 10]


In [12]:
x, y = 5, 90
if x > y
    println("$x > $y")
elseif x < y
    println("$x < $y")
else
    println("$x == $y")
end

5 < 90


In [13]:
x > y ? x : y

90