In [1]:
A = rand(1:4, 3, 3)

3×3 Array{Int64,2}:
 2  4  2
 4  1  4
 2  2  2

In [2]:
B = A
C = copy(A)
[B C]

3×6 Array{Int64,2}:
 2  4  2  2  4  2
 4  1  4  4  1  4
 2  2  2  2  2  2

In [3]:
A[1] = 17
[B C]

3×6 Array{Int64,2}:
 17  4  2  2  4  2
  4  1  4  4  1  4
  2  2  2  2  2  2

In [4]:
x = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [6]:
b = A*x

3-element Array{Float64,1}:
 23.0
  9.0
  6.0

In [7]:
Asym = A + A'

3×3 Array{Int64,2}:
 34  8  4
  8  2  6
  4  6  4

In [10]:
Apd = A'A

3×3 Array{Int64,2}:
 309  76  54
  76  21  16
  54  16  24

In [11]:
A\b

3-element Array{Float64,1}:
 1.0
 1.0000000000000002
 0.9999999999999999

In [13]:
Atall = A[:, 1:2]
display(Atall)
Atall\b #Least Square Solution

3×2 Array{Int64,2}:
 17  4
  4  1
  2  2

2-element Array{Float64,1}:
 0.8849929873772792
 2.178120617110799

In [14]:
A = randn(3, 3)

3×3 Array{Float64,2}:
  0.447347   0.668281   0.243149
  0.59711   -1.70295   -0.384395
 -0.67508   -0.731959  -1.30651

In [16]:
[A[:, 1] A[:, 1]]\b #Smallest Norm Solution

2-element Array{Float64,1}:
 5.73517183695332
 5.7351718369533184

In [18]:
Ashort = A[1:2,:]
display(Ashort)
Ashort\b[1:2]

2×3 Array{Float64,2}:
 0.447347   0.668281   0.243149
 0.59711   -1.70295   -0.384395

3-element Array{Float64,1}:
 37.98597421934284
  6.47391023468586
  6.912255297328558