In [1]:
A = randn(3, 3)

3×3 Array{Float64,2}:
  0.154397   1.08306    -1.18045
 -0.716013  -0.0773396   1.46216
  0.708125   0.140221   -0.0353529

In [2]:
using LinearAlgebra

In [3]:
l, u, p = lu(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
  1.0       0.0        0.0
 -0.215635  1.0        0.0
 -0.988983  0.0597667  1.0
U factor:
3×3 Array{Float64,2}:
 -0.716013  -0.0773396   1.46216
  0.0        1.06638    -0.865155
  0.0        0.0         1.46241

In [4]:
display(norm(l*u-A))
display(norm(l*u-A[p,:]))

4.2632225614997585

5.551115123125783e-17

In [5]:
l, u, p = lu(A, Val(false))
norm(l*u-A)

1.340625907590245e-15

In [6]:
x = ones(3)
b = A*x

3-element Array{Float64,1}:
 0.057005620335914386
 0.6688113099986255
 0.8129932684830075

In [7]:
l, u, p = lu(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
  1.0       0.0        0.0
 -0.215635  1.0        0.0
 -0.988983  0.0597667  1.0
U factor:
3×3 Array{Float64,2}:
 -0.716013  -0.0773396   1.46216
  0.0        1.06638    -0.865155
  0.0        0.0         1.46241

In [8]:
pm = Matrix(Diagonal(ones(3)))[p, :]

3×3 Array{Float64,2}:
 0.0  1.0  0.0
 1.0  0.0  0.0
 0.0  0.0  1.0

In [9]:
u\(l\(pm*b))

3-element Array{Float64,1}:
 1.0
 0.9999999999999998
 1.0

In [10]:
lu(A)\b

3-element Array{Float64,1}:
 1.0000000000000002
 1.0
 1.0000000000000002

In [11]:
det(A)

1.1166106776996456

In [12]:
det(pm)det(u)

1.1166106776996456

In [13]:
q, r = qr(A[:, 1:2])

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.151548  -0.987526   -0.0427304
  0.7028    -0.13805     0.697864
 -0.695058   0.0757291   0.714955
R factor:
2×2 Array{Float64,2}:
 -1.0188  -0.315952
  0.0     -1.04825

In [14]:
q*ones(2)

3-element Array{Float64,1}:
 -1.1390740549228107
  0.5647500078646055
 -0.6193284476096935

In [15]:
q*ones(3)

3-element Array{Float64,1}:
 -1.1818045029884896
  1.2626138542343393
  0.09562620881136019

In [16]:
#ERROR q*ones(4) q*ones(1)

In [17]:
q[1]

-0.15154823723554367

In [18]:
qr(A[:, 1:2])\b

2-element Array{Float64,1}:
 0.07600682764678417
 0.08304964224083479

In [19]:
q, r, p = qr([A[:, 1] A[:, 1]], Val(true))

QRPivoted{Float64,Array{Float64,2}}
Q factor:
3×3 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.151548  0.7028    -0.695058
  0.7028    0.571075   0.4242
 -0.695058  0.4242     0.580474
R factor:
2×2 Array{Float64,2}:
 -1.0188  -1.0188
  0.0      0.0
permutation:
2-element Array{Int64,1}:
 1
 2

In [20]:
qr([A[:, 1] A[:, 1]], Val(true))\b

2-element Array{Float64,1}:
 0.050881146084997775
 0.05088114608499778

In [21]:
Asym = A+A'
AsymEig = eigen(Asym)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
3-element Array{Float64,1}:
 -1.8764239893345112
  0.46332369269878937
  1.49651011794217
vectors:
3×3 Array{Float64,2}:
  0.261908   0.962095   0.0760051
 -0.686825   0.241139  -0.685655
  0.677993  -0.127377  -0.723948

In [22]:
AsymEig.values

3-element Array{Float64,1}:
 -1.8764239893345112
  0.46332369269878937
  1.49651011794217

In [23]:
AsymEig.vectors

3×3 Array{Float64,2}:
  0.261908   0.962095   0.0760051
 -0.686825   0.241139  -0.685655
  0.677993  -0.127377  -0.723948

In [26]:
Asvd = svd(A[:, 1:2])

SVD{Float64,Float64,Array{Float64,2}}
U factor:
3×2 Array{Float64,2}:
 -0.787743  -0.61452
  0.416624  -0.582589
 -0.453746   0.531935
singular values:
2-element Array{Float64,1}:
 1.2041897953602767
 0.8868685467474354
Vt factor:
2×2 Array{Float64,2}:
 -0.615553  -0.788096
  0.788096  -0.615553

In [27]:
Asvd\b

2-element Array{Float64,1}:
 0.07600682764678404
 0.08304964224083501

In [28]:
A

3×3 Array{Float64,2}:
  0.154397   1.08306    -1.18045
 -0.716013  -0.0773396   1.46216
  0.708125   0.140221   -0.0353529

In [29]:
Diagonal(diag(A))

3×3 Diagonal{Float64,Array{Float64,1}}:
 0.154397    ⋅           ⋅ 
  ⋅        -0.0773396    ⋅ 
  ⋅          ⋅         -0.0353529

In [30]:
Diagonal(A)

3×3 Diagonal{Float64,Array{Float64,1}}:
 0.154397    ⋅           ⋅ 
  ⋅        -0.0773396    ⋅ 
  ⋅          ⋅         -0.0353529

In [31]:
Symmetric(Asym)

3×3 Symmetric{Float64,Array{Float64,2}}:
  0.308795   0.367044  -0.472324
  0.367044  -0.154679   1.60239
 -0.472324   1.60239   -0.0707057

In [32]:
LowerTriangular(A)

3×3 LowerTriangular{Float64,Array{Float64,2}}:
  0.154397    ⋅           ⋅ 
 -0.716013  -0.0773396    ⋅ 
  0.708125   0.140221   -0.0353529

In [33]:
SymTridiagonal(diag(Asym), diag(Asym, 1))

3×3 SymTridiagonal{Float64,Array{Float64,1}}:
 0.308795   0.367044    ⋅ 
 0.367044  -0.154679   1.60239
  ⋅         1.60239   -0.0707057

In [34]:
n = 1000
A = randn(n, n)
Asym1 = A+A'
Asym2 = copy(Asym1); Asym2[1,2] += 5eps();
println(issymmetric(Asym1))
println(issymmetric(Asym2))

true
false


In [36]:
@time eigvals(Asym1);

  0.157446 seconds (12 allocations: 7.989 MiB, 6.73% gc time)


In [37]:
@time eigvals(Asym2);

  1.523691 seconds (14 allocations: 7.921 MiB)


In [38]:
@time eigvals(Symmetric(Asym2));

  0.155276 seconds (6.70 k allocations: 8.324 MiB)


In [39]:
rand(1:10, 3, 3)*rand(1:10, 3, 3)

3×3 Array{Int64,2}:
 182  131  135
 110   68   62
 191  135  146

In [43]:
Ar = convert(Matrix{Rational{BigInt}}, rand(1:10, 3, 3))/10

3×3 Array{Rational{BigInt},2}:
 9//10  1//1   7//10
 3//10  2//5   4//5
 1//1   9//10  1//5

In [44]:
x = ones(Int, 3)
b = Ar*x

3-element Array{Rational{BigInt},1}:
 13//5
  3//2
 21//10

In [45]:
lu(Ar)

LU{Rational{BigInt},Array{Rational{BigInt},2}}
L factor:
3×3 Array{Rational{BigInt},2}:
 1//1    0//1   0//1
 9//10   1//1   0//1
 3//10  13//19  1//1
U factor:
3×3 Array{Rational{BigInt},2}:
 1//1   9//10    1//5
 0//1  19//100  13//25
 0//1   0//1    73//190